development:
  adapter: postgresql
  encoding: unicode
  database: clocking_development
  pool: 5
  username:
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: clocking_test
  pool: 5
  username: cess
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: clocking_production
  pool: 5
